---
title: "Data Analysis"
author: "Yao Yu"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Loading necessary libraries
library(tidyverse)
library(janitor)
library(readxl)
library(scales)
library(rjson)
library(stargazer)
library(jtools)
library(xtable)

# Election results data from MIT Election Labs
results_2000_2016 <- read_csv("raw-data/countypres_2000-2016.csv",
                              col_types = cols(
                                                year = col_double(),
                                                state = col_character(),
                                                state_po = col_character(),
                                                county = col_character(),
                                                FIPS = col_double(),
                                                office = col_character(),
                                                candidate = col_character(),
                                                party = col_character(),
                                                candidatevotes = col_double(),
                                                totalvotes = col_double(),
                                                version = col_double()
                                              )) %>% 
  clean_names()

# Religious Census data
religion_2010 <- read_xlsx("raw-data/U.S. Religion Census Religious Congregations and Membership Study, 2010 (County File).XLSX") %>% 
  clean_names()

# Trump Speeches Metadata
speeches_meta <- fromJSON(file = "../../../../Downloads/Trump_Campaign_Corpus-master/trump_campaign_corpus.json")

# Speeches fips data
speech_fips <- read_csv("raw-data/speech_city_state.csv", 
                        col_types = cols(
                                          city_state = col_character(),
                                          n = col_double(),
                                          fips = col_character()
                                        )) %>% 
  select(-n) %>% 
  mutate(fips = as.numeric(fips))

# Religious Terms
religious_terms <- read_csv("raw-data/religious_words.csv",
                            col_types = cols(
                                              religious_words = col_character(),
                                              religious_words_2 = col_character()
                                            )) %>% 
  pull(religious_words)

# Voter Registration Data
voter_reg <- read_xlsx("raw-data/Turnout_Data_2016.xlsx", sheet = "County VTO") %>% 
  clean_names() %>% 
  select(republican_16, fips) %>% 
  drop_na() %>% 
  filter(republican_16 != "-") %>% 
  mutate(republican_16 = as.numeric(republican_16) * 100) %>% 
  rename(prop_rep = republican_16)
```

```{r data cleaning}
# Cleaning MIT Election Labs Data
# 2012 Data
results_2012_clean <- results_2000_2016 %>% 
  filter(year == 2012,
         party == "republican") %>% 
  mutate(propvotes = candidatevotes / totalvotes) %>% 
  select(fips, propvotes)

# 2016 Data
results_2016_clean <- results_2000_2016 %>% 
  filter(year == 2016,
         party == "republican") %>% 
  mutate(propvotes = candidatevotes / totalvotes) %>% 
  select(fips, propvotes)

# Selecting variables of interest in religion dataset
# Mainly broad category of religion rates, fips, and population
religion_clean <- religion_2010 %>% 
  select(totrate, evanrate, bprtrate, mprtrate, 
         cathrate, orthrate, othrate, fips, pop2010)

# Joining 2016 election results with religious census
results_2016_full <- results_2016_clean %>% 
  inner_join(religion_clean, by = "fips") %>% 
  mutate(prop_evan = evanrate/totrate) %>% 
  select(fips, prop_evan, propvotes)
```

```{r speech corpus cleaning}
# Variables of interest from the broader dataset
types <- c()
cities <- c()
states <- c()
text <- c()
filename <- c()

# Loop through the JSON file to select variables of interest
for (i in 1:length(speeches_meta)) {
  types <- c(types, speeches_meta[i][[1]]$genre)
  if (is.null(speeches_meta[i][[1]]$location$city)) {
    cities <- c(cities, NA)
  } else {
    cities <- c(cities, speeches_meta[i][[1]]$location$city)
  }
  if (is.null(speeches_meta[i][[1]]$location$state)) {
    states <- c(states, NA)
  } else {
    states <- c(states, speeches_meta[i][[1]]$location$state)
  }
  if (is.null(speeches_meta[i][[1]]$doc[[1]])) {
    text <- c(text, NA)
  } else {
    text <- c(text, paste(speeches_meta[i][[1]]$doc, collapse = " "))
  }
  filename <- c(filename, speeches_meta[i][[1]]$text_filename)
}

# Save variables of interest into a tibble and filter for only speeches
speeches <- tibble(value = 1:length(speeches_meta), 
       type = types,
       filename = filename,
       city = cities,
       state = states,
       text = text,
       term_count = 0) %>% 
  filter(type == "speech")

# Adding in the fips of each speech location
speeches_clean <- speeches %>% 
  mutate(city_state = paste(city, state, sep = ", ")) %>% 
  inner_join(speech_fips, by = "city_state") %>% 
  drop_na(fips)
```

\setcounter{table}{0}

```{r religious terms table, results='asis'}
terms_table <- tibble(a1 = religious_terms[1:34],
                      a2 = religious_terms[35:68],
                      a3 = religious_terms[69:102])
names(terms_table) <- c("", "", "")

print(xtable(terms_table, caption = c("102 Religious Terms used in Analysis")), comment=FALSE, include.rownames=FALSE, caption.placement = 'top')
```

\setcounter{table}{0}

```{r counting religious terms}
# Counting the number of religious terms that appear in each speech
for (term in religious_terms) {
  speeches_clean <- speeches_clean %>% 
    mutate(term_count = str_detect(text, 
                                   regex(paste("\\W", term, "\\W", sep = ""), 
                                         ignore_case = TRUE)) + term_count)
}
```

```{r first regression, results='asis'}
# Swing States in 2016
# https://constitutioncenter.org/blog/what-are-the-really-swing-states-in-the-2016-election/
swing_staets_2016 <- c("CO", "FL", "IA", "MI", "MN", "NV", 
                       "NH", "NC", "OH", "PA", "VA")

# First regression
data_full <- speeches_clean %>% 
  left_join(results_2016_full, by = "fips") %>% 
  drop_na(prop_evan) %>% 
  mutate(prop_evan = prop_evan * 100,
         swing_state = ifelse(state %in% swing_staets_2016, TRUE, FALSE))

fit_1 <- glm(formula = term_count ~ prop_evan + swing_state, data = data_full, 
             family = poisson(link = "log"))

# Using quasipoisson to correct for over-dispersion because the residual
# deviance is greater than the degrees of freedom
fit_2 <- glm(formula = term_count ~ prop_evan + swing_state, data = data_full, 
             family = quasipoisson(link = "log"))

stargazer(fit_2, type = "latex", header = FALSE,
          title = "Quasi-Poisson Regression",
          dep.var.labels = "Number of Religious Terms", 
          covariate.labels = c("Percent Evangelical in County",
                               "Is A Swing State",
                               "Constant"))
```

```{r first regression plots, warning=FALSE, message=FALSE}
# Hiding warning and message from quasipoisson output
# Plotting the first regression coefficients
figure_1 <- plot_summs(fit_2, scale = TRUE, plot.distributions = TRUE,
           coefs = c("Swing State" = "swing_stateTRUE",
                     "Proportion Evangelical" = "prop_evan")) +
  labs(title = "Quasi-Poisson Regression")

figure_1

# Saving plot as image
# png("graphics/figure_1.png", units="in", width=7, height=5, res=300)
# print(figure_1)
# dev.off()

# Getting predictions from model to graph
new_data_fit_2 <- tibble(prop_evan = rep(seq(0, 82, by = 1), 2),
                         swing_state = c(rep(TRUE, 83), rep(FALSE, 83)))
fit_2_predictions <- predict(fit_2, newdata = new_data_fit_2)
new_data_fit_2 <- new_data_fit_2 %>% 
  mutate(preds = fit_2_predictions)

# Figure 2: Results of Model 1 evaluating the relationship between the percent
# of people in a county that are evangelical and the frequency of religious
# rhetoric that Trump uses in his speeches.
figure_2 <- ggplot() +
  geom_point(aes(x = prop_evan, y = term_count, color = swing_state), 
             alpha = 0.5, data = data_full) +
  geom_line(aes(x = prop_evan, y = preds, color = swing_state), 
            data = new_data_fit_2) +
  scale_x_continuous(breaks = seq(0, 100, by = 10), 
                     labels = percent_format(scale = 1)) +
  scale_y_continuous(breaks = seq(0, 10, by = 2)) +
  scale_color_manual(values=c("#00BFC4", "#F8766D"), 
                     breaks = c("TRUE", "FALSE"),
                     labels = c("County in Swing State", "County Not in Swing State")) +
  theme_minimal() +
  theme(legend.position="bottom") +
  labs(title = "Number of Religious Terms by Percent Evangelical in County",
       x = "Percent Evangelical in County",
       y = "Number of Religious Terms",
       color = "")

figure_2

# Saving plot as image
# png("graphics/figure_2.png", units="in", width=7, height=5, res=300)
# print(figure_2)
# dev.off()
```

```{r second regression, results='asis'}
# Control Variable: 2016 results minus 2012 results
results_diff <- results_2016_full %>% 
  inner_join(results_2012_clean, by = "fips") %>% 
  mutate(diff_propvotes = (propvotes.x - propvotes.y) * 100) %>% 
  select(fips, prop_evan, diff_propvotes)

# Second Regression without control
data_full_two <- speeches_clean %>% 
  left_join(results_diff, by = "fips") %>% 
  drop_na(prop_evan)

fit_3 <- lm(formula = diff_propvotes ~ term_count, 
            data = data_full_two)

# Second Regression w/ control
data_full_three <- speeches_clean %>% 
  left_join(results_diff, by = "fips") %>% 
  inner_join(voter_reg, by = "fips") %>% 
  drop_na(prop_evan)

fit_4 <- lm(formula = diff_propvotes ~ term_count + prop_rep, 
            data = data_full_three)

stargazer(fit_3, fit_4, type = "latex", header = FALSE,
          title = "OLS Regression",
          dep.var.labels = "2016-2012 Rep Vote Difference",
          column.labels = c("No Control", "With Control"),
          covariate.labels = c("Number of Religious Terms",
                               "Percent of County Registered Republican",
                               "Constant"))
```

```{r second regression plots}
# Plotting the second regression coefficients
figure_3 <- plot_summs(fit_3, fit_4, scale = TRUE, plot.distributions = TRUE,
           model.names = c("without control", "with control"),
           coefs = c("Religious Terms" = "term_count",
                     "Registered Republican Proportion" = "prop_rep")) +
  labs(title = "OLS Regression")

figure_3

# Saving plot as image
# png("graphics/figure_3.png", units="in", width=7, height=5, res=300)
# print(figure_3)
# dev.off()

# Getting predictions from model to graph
new_data_fit_4 <- tibble(term_count = rep(seq(0, 10, by = 1), 3),
                         prop_rep = c(rep(25, 11), rep(50, 11), rep(75, 11)))
fit_4_predictions <- predict(fit_4, newdata = new_data_fit_4)
new_data_fit_4 <- new_data_fit_4 %>% 
  mutate(preds = fit_4_predictions,
         prop_rep = as.factor(prop_rep))

# Figure 4: Results of Model 4 evaluating the relationship between the
# difference in votes been 2016 and 2012 and the frequency of religious rhetoric
# that Trump uses in his speeches.
figure_4 <- ggplot() +
  geom_point(aes(x = term_count, y = diff_propvotes), 
             data = data_full_three) +
  geom_line(aes(x = term_count, y = preds, color = prop_rep), 
            data = new_data_fit_4) +
  scale_x_continuous(breaks = seq(0, 10, by = 2)) +
  scale_y_continuous(labels = percent_format(scale = 1)) +
  scale_color_manual(values=c("#F8766D", "#00BA38", "#619CFF"), 
                     breaks = c(25, 50, 75),
                     labels = c("25%", "50%", "75%")) +
  theme_minimal() +
  theme(legend.position="bottom") +
  labs(title = "Difference of Votes Between 2012 and 2016 by Number of Religious Terms",
       x = "Number of Religious Terms",
       y = "Difference of Votes Between 2012 and 2016",
       color = "Percent of County Registered Republican in 2016")

figure_4

# Saving plot as image
# png("graphics/figure_4.png", units="in", width=7, height=5, res=300)
# print(figure_4)
# dev.off()
```
